// Generated by CoffeeScript 1.10.0
(function() {
  var MessageModel, MessageRouter, MessageView, messageRouter;

  MessageModel = Backbone.Model.extend({
    urlRoot: '../api/example_1.php',
    defaults: function() {
      return {
        message: 'Text Message'
      };
    }
  });

  MessageView = Backbone.View.extend({
    template: _.template($('#tpl-hello-backbone').html()),
    render: function(eventName) {
      $(this.el).html(this.template(this.model.toJSON()));
      return this;
    }
  });

  MessageRouter = Backbone.Router.extend({
    routes: {
      '': 'displayMessage'
    },
    displayMessage: function() {
      var messageModel, messageView;
      messageModel = new MessageModel();
      messageView = new MessageView({
        model: messageModel
      });
      messageModel.fetch({
        success: function() {
          return $('#msg').html(messageView.render().el);
        }
      });
    }
  });

  messageRouter = new MessageRouter();

  Backbone.history.start();

}).call(this);
