// Generated by CoffeeScript 1.10.0
(function() {
  var MessageCollection, MessageListItemView, MessageListView, MessageModel, MessageRouter, messageRouter;

  MessageModel = Backbone.Model.extend({
    defaults: {
      code: 0,
      message: 'Test Message'
    }
  });

  MessageRouter = Backbone.Router.extend({
    routes: {
      '': 'displayMessages'
    },
    displayMessages: function() {
      var messageCollection, messageListView, msg1, msg2, msg3, msg4;
      msg1 = new MessageModel({
        code: '001',
        message: 'Registration Success'
      });
      msg2 = new MessageModel({
        code: '002',
        message: 'Registration Fail'
      });
      msg3 = new MessageModel({
        code: '003',
        message: 'Login Success'
      });
      msg4 = new MessageModel({
        code: '003',
        message: 'Login Fail'
      });
      messageCollection = new MessageCollection([msg1, msg2, msg3, msg4]);
      messageListView = new MessageListView({
        model: messageCollection
      });
      messageCollection.fetch({
        success: function() {
          $('#messageList').html(messageListView.render().el);
        }
      });
    }
  });

  MessageCollection = Backbone.Collection.extend({
    model: MessageModel,
    url: '../api/example_2.php'
  });

  MessageListView = Backbone.View.extend({
    tagName: 'ul',
    render: function(eventName) {
      _.each(this.model.models, (function(msg) {
        $(this.el).append(new MessageListItemView({
          model: msg
        }).render().el);
      }), this);
      return this;
    }
  });

  MessageListItemView = Backbone.View.extend({
    tagName: 'li',
    template: _.template($('#tpl-message-item').html()),
    render: function(eventName) {
      $(this.el).html(this.template(this.model.toJSON()));
      return this;
    }
  });

  messageRouter = new MessageRouter();

  Backbone.history.start();

}).call(this);
